apiVersion: v1
kind: Namespace
metadata:
  name: under-construction
---
apiVersion: v1
kind: Secret
metadata:
  name: the-secrets
  namespace: under-construction
type: Opaque
data:
  # env configuration base64 encoded
---
apiVersion: v1
kind: Service
metadata:
  name: temporary-home-service
  namespace: under-construction
spec:
  selector:
    app: landing-page
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporary-home-deployment
  namespace: under-construction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: landing-page
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: SuperSecretRepo:tag
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: the-secrets
      imagePullSecrets:
        - name: ExtraSecretKey
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: temporary-home-ingress
  namespace: under-construction
spec:
  ingressClassName: nginx
  rules:
    - host: www.vl360-interactive.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
