apiVersion: v1
kind: Namespace
metadata:
  name: under-construction
---
apiVersion: v1
kind: Secret
metadata:
  name: temporary-secrets
  namespace: under-construction
type: Opaque
data:
  #env key pairs Base64-encoded for extra obscurity
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporary-home-deployment
  namespace: under-construction
spec:
  replicas: 3
  selector:
    matchLabels:
      app: home
  template:
    metadata:
      labels:
        app: landing-page
    spec:
      containers:
        - name: landing-page
          image: SuperSecretRepository:DesiredTag
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: temporary-secrets
      imagePullSecrets:
        - name: SuperSecretCredentials
---
apiVersion: v1
kind: Service
metadata:
  name: temporary-home-ingress
  namespace: under-construction
spec:
  ingressClassName: nginx
  rules:
    - host: www.vl360-interactive.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing-page
                port:
                  number: 80
